---
- name: copy file
  hosts: webservers
  tasks:
   - name: copy file to webservers
     ansible.builtin.copy:
      src: ./textfile.txt
      dest: /home/ec2-user/textfile.txt
      mode: preserve

- name: copy file to ubuntu
  hosts: ubuntu
  tasks:
   - name: copy file to ubuntu
     ansible.builtin.copy:
      src: ./textfile.txt
      dest: /home/ubuntu/textfile.txt
      mode: preserve